apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: yycz852am-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/yycz852am-java-springboot-gitops